# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoadScreenFromMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoadScreen(object):
    def setupUi(self, LoadScreen):
        LoadScreen.setObjectName("LoadScreen")
        LoadScreen.resize(846, 404)
        self.centralwidget = QtWidgets.QWidget(LoadScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(56,58,89);\n"
"    border-radius: 10px;\n"
"    color: rgb(220, 220, 220);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 70, 831, 161))
        self.label.setStyleSheet("color: rgb(254,121,199);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(270, 280, 301, 23))
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    background-color: rgb(98,114,164);\n"
"    color: rgb(200,200,200);\n"
"    border-style: none;\n"
"    border-radius: 10px;\n"
"    text-align: center;\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0.523, x2:1, y2:0.534, stop:0 rgba(176, 84, 138, 255), stop:1 rgba(145, 65, 172, 255));\n"
"\n"
"}\n"
"\n"
"")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.frame)
        LoadScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(LoadScreen)
        QtCore.QMetaObject.connectSlotsByName(LoadScreen)

    def retranslateUi(self, LoadScreen):
        _translate = QtCore.QCoreApplication.translate
        LoadScreen.setWindowTitle(_translate("LoadScreen", "MainWindow"))
        self.label.setText(_translate("LoadScreen", "<html><head/><body><p><span style=\" font-size:72pt;\">MEAVE</span></p></body></html>"))
